---
- hosts: k8s
  tasks:
  - name: executing sample command
    shell: uptime
    register: result

  - name: printing variable
    debug:
      msg: "{{result}}"
    when: ansible_os_family == "RedHat"
